[package]
name = "axum_example"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["process", "tokio-macros"] }

[dev-dependencies]
axum-test = "18.0.2"
