[package]
name = "axum-websocket-example"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.6", features = ["ws"] }
tokio = { version = "1.48" }

[dev-dependencies]
tokio-tungstenite = "0.28"
futures-util = "0.3"